const hospitalStocks = [
  {
    id: 1,
    category: "사무용 소모품",
    itemName: "주사바늘",
    department: "진료",
    state: "승인",
    quantity: 30,
    measure: "BOX",
    position: "2-carm",
  },
  {
    id: 2,
    category: "사무용품",
    itemName: "노트북",
    department: "진료",
    state: "승인",
    quantity: 15,
    measure: "EA",
    position: "처치실",
  },
  {
    id: 3,
    category: "의료용 소모품",
    itemName: "모니터",
    department: "진료",
    state: "입고 완료",
    quantity: 20,
    measure: "EA",
    position: "2-carm",
  },
  {
    id: 4,
    category: "마케팅 용품",
    itemName: "프린터",
    department: "진료",
    state: "주문 완료",
    quantity: 5,
    measure: "BOX",
    position: "처치실",
  },
  {
    id: 5,
    category: "사무용 소모품",
    itemName: "프린터",
    department: "진료",
    state: "주문 필요",
    quantity: 8,
    measure: "EA",
    position: "2-carm",
  },
  {
    id: 6,
    category: "사무용 소모품",
    itemName: "키보드",
    department: "진료",
    state: "입고 중",
    quantity: 12,
    measure: "EA",
    position: "처치실",
  },
  {
    id: 7,
    category: "의료용 소모품",
    itemName: "마우스",
    department: "진료",
    state: "승인",
    quantity: 25,
    measure: "EA",
    position: "2-carm",
  },
  {
    id: 8,
    category: "마케팅 용품",
    itemName: "프로젝터",
    department: "진료",
    state: "입고 완료",
    quantity: 10,
    measure: "EA",
    position: "처치실",
  },
  {
    id: 9,
    category: "의료용 소모품",
    itemName: "프린터 스캐너",
    department: "진료",
    state: "주문 완료",
    quantity: 3,
    measure: "BOX",
    position: "2-carm",
  },
  {
    id: 10,
    category: "마케팅 용품",
    itemName: "모니터",
    department: "진료",
    state: "주문 필요",
    quantity: 7,
    measure: "EA",
    position: "처치실",
  },

  {
    id: 11,
    category: "사무용 소모품",
    itemName: "볼펜",
    department: "원장님",
    state: "승인",
    quantity: 50,
    measure: "BOX",
    position: "사무실",
  },
  {
    id: 12,
    category: "사무용품",
    itemName: "데스크탑",
    department: "물리치료",
    state: "주문 필요",
    quantity: 5,
    measure: "EA",
    position: "재활실",
  },
  {
    id: 13,
    category: "의료용 소모품",
    itemName: "의료 장갑",
    department: "간호",
    state: "승인",
    quantity: 100,
    measure: "BOX",
    position: "수술실",
  },
  {
    id: 14,
    category: "마케팅 용품",
    itemName: "포스터",
    department: "원장님",
    state: "입고 중",
    quantity: 20,
    measure: "EA",
    position: "홍보실",
  },
  {
    id: 15,
    category: "사무용 소모품",
    itemName: "수첩",
    department: "진료",
    state: "입고 완료",
    quantity: 15,
    measure: "EA",
    position: "사무실",
  },
  {
    id: 16,
    category: "의료용 소모품",
    itemName: "수액세트",
    department: "간호",
    state: "승인",
    quantity: 40,
    measure: "BOX",
    position: "응급실",
  },
  {
    id: 17,
    category: "사무용품",
    itemName: "서류함",
    department: "원장님",
    state: "입고 완료",
    quantity: 10,
    measure: "EA",
    position: "사무실",
  },
  {
    id: 18,
    category: "의료용 소모품",
    itemName: "혈압계",
    department: "진료",
    state: "주문 완료",
    quantity: 7,
    measure: "EA",
    position: "진료실",
  },
  {
    id: 19,
    category: "마케팅 용품",
    itemName: "배너",
    department: "원장님",
    state: "승인",
    quantity: 5,
    measure: "EA",
    position: "로비",
  },
  {
    id: 20,
    category: "사무용 소모품",
    itemName: "마커펜",
    department: "진료",
    state: "입고 중",
    quantity: 25,
    measure: "EA",
    position: "사무실",
  },

  {
    id: 21,
    category: "의료용 소모품",
    itemName: "청진기",
    department: "진료",
    state: "승인",
    quantity: 15,
    measure: "EA",
    position: "진료실",
  },
  {
    id: 22,
    category: "사무용품",
    itemName: "서랍장",
    department: "간호",
    state: "입고 완료",
    quantity: 4,
    measure: "EA",
    position: "간호실",
  },
  {
    id: 23,
    category: "의료용 소모품",
    itemName: "알콜 스왑",
    department: "간호",
    state: "주문 필요",
    quantity: 200,
    measure: "BOX",
    position: "소모품실",
  },
  {
    id: 24,
    category: "마케팅 용품",
    itemName: "굿즈 키트",
    department: "홍보",
    state: "입고 중",
    quantity: 10,
    measure: "SET",
    position: "홍보실",
  },
  {
    id: 25,
    category: "의료용 소모품",
    itemName: "산소 마스크",
    department: "응급",
    state: "주문 완료",
    quantity: 30,
    measure: "EA",
    position: "응급실",
  },
  {
    id: 26,
    category: "사무용 소모품",
    itemName: "화이트보드",
    department: "원장님",
    state: "입고 완료",
    quantity: 2,
    measure: "EA",
    position: "회의실",
  },
  {
    id: 27,
    category: "의료용 소모품",
    itemName: "수술 도구 세트",
    department: "수술실",
    state: "승인",
    quantity: 5,
    measure: "SET",
    position: "수술실",
  },
  {
    id: 28,
    category: "사무용품",
    itemName: "전기 포트",
    department: "간호",
    state: "주문 필요",
    quantity: 3,
    measure: "EA",
    position: "간호실",
  },
  {
    id: 29,
    category: "마케팅 용품",
    itemName: "명함 세트",
    department: "원장님",
    state: "승인",
    quantity: 20,
    measure: "BOX",
    position: "홍보실",
  },
  {
    id: 30,
    category: "사무용 소모품",
    itemName: "클립 세트",
    department: "진료",
    state: "입고 완료",
    quantity: 100,
    measure: "BOX",
    position: "사무실",
  },
  {
    id: 31,
    category: "의료용 소모품",
    itemName: "기본 의약품",
    department: "간호",
    state: "승인",
    quantity: 50,
    measure: "BOX",
    position: "응급실",
  },
];

export default hospitalStocks;
