const hospitalStocks = [
  {
    id: 1,
    category: "사무용 소모품",
    itemName: "주사바늘",
    department: "진료",
    state: "승인",
    quantity: 30,
    measure: "BOX",
    position: "2-carm",
  },
  {
    id: 2,
    category: "사무용품",
    itemName: "노트북",
    department: "진료",
    state: "승인",
    quantity: 15,
    measure: "EA",
    position: "처치실",
  },
  {
    id: 3,
    category: "의료용 소모품",
    itemName: "모니터",
    department: "진료",
    state: "입고 완료",
    quantity: 20,
    measure: "EA",
    position: "2-carm",
  },
  {
    id: 4,
    category: "마케팅 용품",
    itemName: "프린터",
    department: "진료",
    state: "주문 완료",
    quantity: 5,
    measure: "BOX",
    position: "처치실",
  },
  {
    id: 5,
    category: "사무용 소모품",
    itemName: "프린터",
    department: "진료",
    state: "주문 필요",
    quantity: 8,
    measure: "EA",
    position: "2-carm",
  },
  {
    id: 6,
    category: "사무용 소모품",
    itemName: "키보드",
    department: "진료",
    state: "입고 중",
    quantity: 12,
    measure: "EA",
    position: "처치실",
  },
  {
    id: 7,
    category: "의료용 소모품",
    itemName: "마우스",
    department: "진료",
    state: "승인",
    quantity: 25,
    measure: "EA",
    position: "2-carm",
  },
  {
    id: 8,
    category: "마케팅 용품",
    itemName: "프로젝터",
    department: "진료",
    state: "입고 완료",
    quantity: 10,
    measure: "EA",
    position: "처치실",
  },
  {
    id: 9,
    category: "의료용 소모품",
    itemName: "프린터 스캐너",
    department: "진료",
    state: "주문 완료",
    quantity: 3,
    measure: "BOX",
    position: "2-carm",
  },
  {
    id: 10,
    category: "마케팅 용품",
    itemName: "모니터",
    department: "진료",
    state: "주문 필요",
    quantity: 7,
    measure: "EA",
    position: "처치실",
  },
];

export default hospitalStocks;
