export const tasks = [
  // 간호팀 업무
  {
    id: "1",
    title: "바이탈 체크",
    priority: "상",
    category: "일반",
    writer: "수간호사",
    assignee: "간호사",
    startDate: "2024/03/01",
    endDate: "2024/03/31",
    cycle: "매일",
    department: "간호팀",
    location: "2층 간호스테이션",
    status: "진행중",
    description: "입원 환자 바이탈 체크 및 기록",
    completedBy: null,
    days: ["월", "화", "수", "목", "금", "토", "일"],
  },
  {
    id: "2",
    title: "약품 재고 확인",
    priority: "중",
    category: "일반",
    writer: "수간호사",
    assignee: "약제팀장",
    startDate: "2024/03/01",
    endDate: "2024/06/30",
    cycle: "매주",
    department: "간호팀",
    location: "약제실",
    status: "진행중",
    description: "주요 약품 재고 확인 및 발주 요청",
    completedBy: null,
    days: ["월", "수", "금"],
  },

  // 원무팀 업무
  {
    id: "3",
    title: "일일 수납 정산",
    priority: "상",
    category: "일반",
    writer: "원무팀장",
    assignee: "원무팀",
    startDate: new Date(),
    endDate: new Date(),
    cycle: "매일",
    department: "원무팀",
    location: "원무과",
    status: "진행중",
    description: "당일 수납 내역 정산 및 마감",
    completedBy: null,
  },

  // 진료팀 업무
  {
    id: "4",
    title: "진료 기록 작성",
    priority: "상",
    category: "일반",
    writer: "진료부장",
    assignee: "진료의",
    startDate: new Date(),
    endDate: new Date(),
    cycle: "매일",
    department: "진료팀",
    location: "진료실",
    status: "진행중",
    description: "환자 진료 기록 작성 및 검토",
    completedBy: null,
  },

  // 경영지원팀 업무
  {
    id: "5",
    title: "직원 급여 정산",
    priority: "상",
    category: "일반",
    writer: "경영지원팀장",
    assignee: "경영지원팀",
    startDate: new Date(2024, 2, 25),
    endDate: new Date(2024, 3, 5),
    cycle: "매월",
    department: "경영지원팀",
    location: "경영지원실",
    status: "진행중",
    description: "직원 급여 및 수당 정산",
    completedBy: null,
  },

  // 전체 공통 업무
  {
    id: "6",
    title: "감염관리 교육",
    priority: "상",
    category: "이벤트",
    writer: "감염관리실장",
    assignee: "전체",
    startDate: new Date(2024, 1, 15),
    endDate: new Date(2024, 1, 15),
    cycle: "격주",
    department: "전체",
    location: "강당",
    status: "예정",
    description: "전직원 감염관리 수칙 교육",
    completedBy: null,
  },

  // 시설관리팀 업무
  {
    id: "7",
    title: "의료장비 점검",
    priority: "상",
    category: "일반",
    writer: "이시설",
    assignee: "시설팀",
    startDate: new Date(2024, 2, 1),
    endDate: new Date(2024, 8, 30),
    cycle: "매일",
    department: "시설관리팀",
    status: "진행중",
    description: "주요 의료장비 작동 상태 점검",
    completedBy: null,
  },
  {
    id: "8",
    title: "소독/방역",
    priority: "중",
    category: "일반",
    writer: "이시설",
    assignee: "방역담당",
    startDate: new Date(2024, 2, 15),
    endDate: new Date(2024, 3, 14),
    cycle: "매주",
    department: "시설관리팀",
    status: "진행중",
    description: "병원 전체 소독 및 방역 작업",
    completedBy: null,
  },

  // 일회성 업무 예시
  {
    id: "9",
    title: "신규 의료장비 교육",
    priority: "상",
    category: "이벤트",
    writer: "김원장",
    assignee: "의료진",
    startDate: new Date(2024, 2, 1),
    endDate: new Date(2024, 2, 3),
    cycle: "일회성",
    department: "전체",
    status: "예정",
    description: "MRI 장비 업그레이드 관련 교육",
    completedBy: null,
  },
  {
    id: "10",
    title: "소방안전 교육",
    priority: "중",
    category: "이벤트",
    writer: "이시설",
    assignee: "전체",
    startDate: new Date(2024, 2, 15),
    endDate: new Date(2024, 2, 15),
    cycle: "일회성",
    department: "전체",
    status: "예정",
    description: "연례 소방안전 교육 및 훈련",
    completedBy: null,
  },
];
