export const tasks = [
  {
    id: 1,
    taskName: "월간 보고서 작성",
    writer: "홍길동",
    manager: "이영희",
    category: "일반",
    priority: "보통",
    startDate: "2025-03-01",
    frequency: "매월",
    days: ["월요일"],
  },
  {
    id: 2,
    taskName: "주간 회의 준비",
    writer: "이순신",
    manager: "김민재",
    category: "일반",
    priority: "보통",
    startDate: "2025-03-03",
    frequency: "매주",
    days: ["수요일"],
  },
  {
    id: 3,
    taskName: "고객 방문 일정 조율",
    writer: "김유신",
    manager: "박지성",
    category: "이벤트",
    priority: "보통",
    startDate: "2025-03-05",
    frequency: "일회성",
    days: ["목요일"],
  },
  {
    id: 4,
    taskName: "제품 검수 및 평가",
    writer: "최민호",
    manager: "홍진호",
    category: "일반",
    priority: "보통",
    startDate: "2025-03-06",
    frequency: "일회성",
    days: ["금요일"],
  },
  {
    id: 5,
    taskName: "신규 프로젝트 기획 회의",
    writer: "박세리",
    manager: "이영희",
    category: "이벤트",
    priority: "보통",
    startDate: "2025-03-07",
    frequency: "일회성",
    days: ["토요일"],
  },
  {
    id: 6,
    taskName: "인사 발령 공지",
    writer: "김정은",
    manager: "홍길동",
    category: "기타",
    priority: "보통",
    startDate: "2025-03-08",
    frequency: "일회성",
    days: ["일요일"],
  },
  {
    id: 7,
    taskName: "마케팅 자료 제작",
    writer: "이민호",
    manager: "김민재",
    category: "일반",
    priority: "보통",
    startDate: "2025-03-09",
    frequency: "일회성",
    days: ["월요일"],
  },
  {
    id: 8,
    taskName: "재고 관리 업데이트",
    writer: "홍길동",
    manager: "박지성",
    category: "상시",
    priority: "보통",
    startDate: "2025-03-10",
    frequency: "매주",
    days: ["화요일", "목요일"],
  },
  {
    id: 9,
    taskName: "시스템 점검",
    writer: "이순신",
    manager: "최민호",
    category: "상시",
    priority: "보통",
    startDate: "2025-03-11",
    frequency: "매월",
    days: ["수요일"],
  },
  {
    id: 10,
    taskName: "교육 세미나 준비",
    writer: "김유신",
    manager: "박세리",
    category: "이벤트",
    priority: "보통",
    startDate: "2025-03-12",
    frequency: "일회성",
    days: ["목요일"],
  },
  {
    id: 11,
    taskName: "고객 피드백 정리",
    writer: "최민호",
    manager: "이민호",
    category: "상시",
    priority: "보통",
    startDate: "2025-03-13",
    frequency: "매주",
    days: ["금요일"],
  },
  {
    id: 12,
    taskName: "사내 행사 기획",
    writer: "박세리",
    manager: "김정은",
    category: "이벤트",
    priority: "보통",
    startDate: "2025-03-14",
    frequency: "일회성",
    days: ["토요일"],
  },
  {
    id: 13,
    taskName: "비용 예산 검토",
    writer: "김민재",
    manager: "홍진호",
    category: "일반",
    priority: "보통",
    startDate: "2025-03-15",
    frequency: "매월",
    days: ["일요일"],
  },
  {
    id: 14,
    taskName: "보안 강화 방안 논의",
    writer: "이영희",
    manager: "김유신",
    category: "일반",
    priority: "보통",
    startDate: "2025-03-16",
    frequency: "일회성",
    days: ["월요일"],
  },
  {
    id: 15,
    taskName: "문서 보관 정리",
    writer: "홍진호",
    manager: "최민호",
    category: "상시",
    priority: "보통",
    startDate: "2025-03-17",
    frequency: "일회성",
    days: ["화요일"],
  },
  {
    id: 16,
    taskName: "클라이언트 미팅",
    writer: "이민호",
    manager: "박지성",
    category: "이벤트",
    priority: "보통",
    startDate: "2025-03-18",
    frequency: "일회성",
    days: ["수요일"],
  },
  {
    id: 17,
    taskName: "웹사이트 업데이트",
    writer: "박지성",
    manager: "김민재",
    category: "상시",
    priority: "보통",
    startDate: "2025-03-19",
    frequency: "일회성",
    days: ["목요일"],
  },
  {
    id: 18,
    taskName: "데이터 백업 확인",
    writer: "김정은",
    manager: "이영희",
    category: "상시",
    priority: "보통",
    startDate: "2025-03-20",
    frequency: "매주",
    days: ["금요일"],
  },
  {
    id: 19,
    taskName: "회의록 작성",
    writer: "최민호",
    manager: "홍길동",
    category: "상시",
    priority: "보통",
    startDate: "2025-03-21",
    frequency: "매주",
    days: ["토요일"],
  },
  {
    id: 20,
    taskName: "신규 채용 면접",
    writer: "박세리",
    manager: "김유신",
    category: "이벤트",
    priority: "보통",
    startDate: "2025-03-22",
    frequency: "일회성",
    days: ["일요일"],
  },
  {
    id: 21,
    taskName: "내부 감사 준비",
    writer: "이순신",
    manager: "홍진호",
    category: "일반",
    priority: "보통",
    startDate: "2025-03-23",
    frequency: "일회성",
    days: ["월요일"],
  },
  {
    id: 22,
    taskName: "기술 지원 요청 처리",
    writer: "김민재",
    manager: "이민호",
    category: "상시",
    priority: "보통",
    startDate: "2025-03-24",
    frequency: "일회성",
    days: ["화요일"],
  },
  {
    id: 23,
    taskName: "프로젝트 마감 보고",
    writer: "홍길동",
    manager: "박세리",
    category: "일반",
    priority: "보통",
    startDate: "2025-03-25",
    frequency: "일회성",
    days: ["수요일"],
  },
  {
    id: 24,
    taskName: "법무 검토 진행",
    writer: "이영희",
    manager: "김정은",
    category: "일반",
    priority: "보통",
    startDate: "2025-03-26",
    frequency: "일회성",
    days: ["목요일"],
  },
  {
    id: 25,
    taskName: "서비스 개선 회의",
    writer: "최민호",
    manager: "박지성",
    category: "기타",
    priority: "보통",
    startDate: "2025-03-27",
    frequency: "매주",
    days: ["금요일", "월요일"],
  },
  {
    id: 26,
    taskName: "시스템 보안 점검",
    writer: "이순신",
    manager: "홍길동",
    category: "상시",
    priority: "보통",
    startDate: "2025-03-28",
    frequency: "매월",
    days: ["토요일"],
  },
  {
    id: 27,
    taskName: "연간 목표 설정",
    writer: "박세리",
    manager: "이민호",
    category: "일반",
    priority: "보통",
    startDate: "2025-03-29",
    frequency: "연간",
    days: ["일요일"],
  },
  {
    id: 28,
    taskName: "협력 업체 연락",
    writer: "김유신",
    manager: "최민호",
    category: "일반",
    priority: "보통",
    startDate: "2025-03-30",
    frequency: "일회성",
    days: ["월요일"],
  },
  {
    id: 29,
    taskName: "고객 만족도 조사",
    writer: "홍진호",
    manager: "김민재",
    category: "이벤트",
    priority: "보통",
    startDate: "2025-03-31",
    frequency: "일회성",
    days: ["화요일"],
  },
  {
    id: 30,
    taskName: "리스크 관리 분석",
    writer: "이민호",
    manager: "박세리",
    category: "일반",
    priority: "보통",
    startDate: "2025-04-01",
    frequency: "일회성",
    days: ["수요일"],
  },
  {
    id: 31,
    taskName: "업무 프로세스 개선",
    writer: "김정은",
    manager: "홍길동",
    category: "일반",
    priority: "보통",
    startDate: "2025-04-02",
    frequency: "일회성",
    days: ["목요일"],
  },
];
