const hospitalStaff = [
  {
    id: 1,
    name: "박상현",
    role: "의사",
    hospitalOwner: true,
    departmentLeader: true,
    department: "진료",
    email: "chulsoo.kim@hospital.com",
    phone: "010-1111-1111",
  },
  {
    id: 2,
    name: "장원영",
    role: "간호부장",
    hospitalOwner: false,
    departmentLeader: true,
    department: "간호",
    email: "younghee.park@hospital.com",
    phone: "010-2222-2222",
  },
  {
    id: 3,
    name: "안유진",
    role: "간호사",
    hospitalOwner: false,
    departmentLeader: false,
    department: "간호",
    email: "younghee.park@hospital.com",
    phone: "010-2222-2222",
  },
  {
    id: 4,
    name: "김이서",
    role: "간호사",
    hospitalOwner: false,
    departmentLeader: false,
    department: "간호",
    email: "younghee.park@hospital.com",
    phone: "010-2222-2222",
  },
  {
    id: 5,
    name: "장가을",
    role: "간호사",
    hospitalOwner: false,
    departmentLeader: false,
    department: "간호",
    email: "younghee.park@hospital.com",
    phone: "010-2222-2222",
  },
  {
    id: 6,
    name: "최예나",
    role: "방사선사 팀장",
    hospitalOwner: false,
    departmentLeader: true,
    department: "영상의학",
    email: "younghee.park@hospital.com",
    phone: "010-2222-2222",
  },
  {
    id: 7,
    name: "김민지",
    role: "물리치료 팀장",
    hospitalOwner: false,
    departmentLeader: true,
    department: "물리치료",
    email: "younghee.park@hospital.com",
    phone: "010-2222-2222",
  },
  {
    id: 8,
    name: "강해린",
    role: "물리치료사",
    hospitalOwner: false,
    departmentLeader: false,
    department: "물리치료",
    email: "younghee.park@hospital.com",
    phone: "010-2222-2222",
  },
  {
    id: 9,
    name: "팜하니",
    role: "물리치료사",
    hospitalOwner: false,
    departmentLeader: false,
    department: "물리치료",
    email: "younghee.park@hospital.com",
    phone: "010-2222-2222",
  },
  {
    id: 10,
    name: "이혜인",
    role: "물리치료사",
    hospitalOwner: false,
    departmentLeader: false,
    department: "물리치료",
    email: "younghee.park@hospital.com",
    phone: "010-2222-2222",
  },
];

export default hospitalStaff;
