// 옵션 배열들을 별도의 변수로 분리
export const departmentArray = [
  "간호팀",
  "물리치료팀",
  "원무팀",
  "방사선팀",
  "진료팀",
  "경영지원팀",
];

export const roleOptions = {
  간호팀: ["팀원", "간호팀장"],
  물리치료팀: ["팀원", "물리치료팀장"],
  원무팀: ["팀원", "원무과장"],
  영상의학팀: ["팀원", "영상의학팀장"],
  진료팀: ["팀원", "대표원장"],
  경영지원팀: ["팀원", "경영지원팀장"],
};

export const locationOptions = {
  간호팀: ["안내 데스크"],
  물리치료팀: [
    "4층 물리치료 데스크",
    "3층 물리치료 데스크",
    "3층 물리치료실 1",
    "3층 물리치료실 2",
  ],
  원무팀: ["원무과장실 PC", "X-RAY실", "초음파실", "C-ARM실"],
  영상의학팀: ["X-RAY실", "초음파실", "C-ARM실"],
  진료팀: ["원장실", "원장실2"],
  경영지원팀: ["경영지원팀 PC"],
};

export const allLocationOptions = Object.values(locationOptions).flat();

const hospitalStaff = [
  {
    id: "박상현",
    name: "박상현",
    role: "원장",
    hospitalOwner: true,
    departmentLeader: true,
    department: "진료팀",
    email: "sanghyun.park@hospital.com",
    phone: "010-1111-1111",
  },
  {
    id: "김혜정",
    name: "김혜정",
    role: "팀원",
    hospitalOwner: false,
    departmentLeader: true,
    department: "간호팀",
    email: "hyejung.kim@hospital.com",
    phone: "010-2222-2222",
  },
  {
    id: "윤예인",
    name: "윤예인",
    role: "팀원",
    hospitalOwner: false,
    departmentLeader: false,
    department: "간호팀",
    email: "yein.yoon@hospital.com",
    phone: "010-3333-3333",
  },
  {
    id: "조은주",
    name: "조은주",
    role: "팀원",
    hospitalOwner: false,
    departmentLeader: false,
    department: "간호팀",
    email: "eunju.cho@hospital.com",
    phone: "010-4444-4444",
  },
  {
    id: "유승은",
    name: "유승은",
    role: "팀원",
    hospitalOwner: false,
    departmentLeader: false,
    department: "간호팀",
    email: "seungeun.yu@hospital.com",
    phone: "010-5555-5555",
  },
  {
    id: "김윤경",
    name: "김윤경",
    role: "팀원",
    hospitalOwner: false,
    departmentLeader: false,
    department: "물리치료팀",
    email: "yunkyung.kim@hospital.com",
    phone: "010-6666-6666",
  },
  {
    id: "윤소희",
    name: "윤소희",
    role: "팀원",
    hospitalOwner: false,
    departmentLeader: false,
    department: "물리치료팀",
    email: "sohee.yoon@hospital.com",
    phone: "010-7777-7777",
  },
  {
    id: "이기현",
    name: "이기현",
    role: "팀원",
    hospitalOwner: false,
    departmentLeader: false,
    department: "물리치료팀",
    email: "kihyun.lee@hospital.com",
    phone: "010-8888-8888",
  },
  {
    id: "이진용",
    name: "이진용",
    role: "물리치료팀장",
    hospitalOwner: false,
    departmentLeader: true,
    department: "물리치료팀",
    email: "jinyong.lee@hospital.com",
    phone: "010-9999-9999",
  },
  {
    id: "정현",
    name: "정현",
    role: "팀원",
    hospitalOwner: false,
    departmentLeader: false,
    department: "물리치료팀",
    email: "hyun.jung@hospital.com",
    phone: "010-1010-1010",
  },
  {
    id: "남호근",
    name: "남호근",
    role: "원무과장",
    hospitalOwner: false,
    departmentLeader: true,
    department: "원무팀",
    email: "hogeun.nam@hospital.com",
    phone: "010-1212-1212",
  },
  {
    id: "유승연",
    name: "유승연",
    role: "방사선팀장",
    hospitalOwner: false,
    departmentLeader: true,
    department: "방사선팀",
    email: "seungyeon.yu@hospital.com",
    phone: "010-1313-1313",
  },
  {
    id: "박상빈",
    name: "박상빈",
    role: "경영지원팀장",
    hospitalOwner: false,
    departmentLeader: true,
    department: "경영지원팀",
    email: "sangbin.park@hospital.com",
    phone: "010-1414-1414",
  },
  {
    id: "지창윤",
    name: "지창윤",
    role: "팀원",
    hospitalOwner: false,
    departmentLeader: false,
    department: "경영지원팀",
    email: "changyun.ji@hospital.com",
    phone: "010-5141-7233",
  },
];

export default hospitalStaff;
